### ISSUE TITLE
error using logpath - pointing to cowrie log folder

### ISSUE THREAD

**Issue by techstartupexplorer** [jslagrew/cowrieprocessor#1]
Any suggestion to solve this ? thanks

# python3 process_cowrie.py --logpath /home/cowrie/cowrie/var/log/cowrie
Processing file /home/cowrie/cowrie/var/log/cowrie/cowrie.json
Traceback (most recent call last):
  File "/home/cowrie/cowrieprocessor/process_cowrie.py", line 626, in <module>
    summarystring += "{:>40s}  {:10s}".format("Most Common Number of Commands:", str(number_of_commands[0])) + "\n"
IndexError: list index out of range

**Comment by jslagrew** [comment]
I'm guessing there was an issue adding in the number of commands for a particular session. Would you be willing to attach your cowrie.json file? I'll do some additional testing on my end. It's possible that there may also be a problem with incomplete data if it's a JSON log file actively been updated by cowrie, which I may need to add some handling for.

**Comment by jslagrew** [comment]
I was able to replicate the issue using my own honeypot as well. Digging into it.

**Comment by jslagrew** [comment]
For now, add in the "summarizedays 1" option, which will process your current active file. 

`python3 process_cowrie.py --logpath /home/cowrie/cowrie/var/log/cowrie --summarizedays 1`

If you want the last 2 days, just swap out the '1' with a '2'.

I'll need to tweak this a bit to output as it had been written originally. In an update the command you used would then just process all of the JSON files in that folder and output each individual attack seen for all files in that directory.

**Comment by techstartupexplorer** [comment]
thank you got it. using API keys with summarizedays works well. i will try your suggestion as well. looks like this will work ;) Very cool Tool!

**Comment by jslagrew** [comment]
Test out using only the 'logpath' option and let me know how it works. I believe I fixed the immediate issue. 

Thanks for the feedback!
